### ISSUE TITLE
URGENT: - Videos not displaying on kingsway republic

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/hogapp#40]
1. The data and videos are being transferred and stored in admin correctly.  However less than 50% are being displayed on the website.

2. We need to have all videos and data showing on website at the moment

**Comment by sebbacon** [comment]
Just to check, I presume you mean the stills are not showing for some of them? i.e. all the videos work fine but for some the preview is a black square?

An example: https://kingsway.hedgehogrepublic.org/admin/api/measurement/42207/change/

**Comment by sebbacon** [comment]
I think it's that the poster-extractor algorithm doesn't work with all videos. Here's one such video:

[bad-video.zip](https://github.com/tech4nature/hogapp/files/5335565/bad-video.zip)

**Comment by Gabrielkyne** [comment]
> Just to check, I presume you mean the stills are not showing for some of them? i.e. all the videos work fine but for some the preview is a black square?
> 
> An example: https://kingsway.hedgehogrepublic.org/admin/api/measurement/42207/change/

The problem was related to videos not showing up on the system though they are in our database.  This can be seen clearly with the locations:

These have weights but no videos:

http://kingsway.hedgehogrepublic.org/location/005
http://kingsway.hedgehogrepublic.org/location/006
http://kingsway.hedgehogrepublic.org/location/007
http://kingsway.hedgehogrepublic.org/location/002

**Comment by sebbacon** [comment]
Taking the [first example](https://kingsway.hedgehogrepublic.org/location/005), I can currently see 13 measurements and then one video from early yesterday morning on the website.

These are the most recent four:

![image](https://user-images.githubusercontent.com/211271/95254989-a5460980-0818-11eb-9640-91ee72946ef4.png)


In the admin interface, [filtered for that location + videos](https://kingsway.hedgehogrepublic.org/admin/api/measurement/?location__code__exact=005&measurement_type__exact=video&observed_at__gte=2020-09-29+00%3A00%3A00%2B00%3A00&observed_at__lt=2020-10-07+00%3A00%3A00%2B00%3A00),  there have been several videos today, the most recent being [](https://kingsway.hedgehogrepublic.org/admin/api/measurement/42341/change) about an hour ago.

**Comment by sebbacon** [comment]
The error is presumably in [this grouping code](https://github.com/tech4nature/hogapp/blob/5d02cf04c333adc0859f1a5fd720b6f9526776f0/hog/frontend/views.py#L203)
