### ISSUE TITLE
URGENT: List of hogs finds all of the hogs from different republics

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/hogapp#42]
1. The list of hogs shows all the hogs on the different republics.  This makes it very confusing to analyse.

2. We need the list to only include the hedgehogs in that republic

**Comment by sebbacon** [comment]
What if hogs roam between republics?

Obviously not a problem right, now, but how do we define the republic a hog "belongs to" in general?

**Comment by sebbacon** [comment]
Oh, I suppose the obvious thing is "a hog belongs to all republics it has visited"
